[build]
  command   = "npx expo export --platform web && mkdir -p dist/images && cp public/images/bali1.jpg.jpg dist/images/bali1.jpg && cp public/images/bali2.jpg.jpg dist/images/bali2.jpg && cp public/images/bali3.jpg.jpg dist/images/bali3.jpg && cp public/images/bali4.jpg.jpg dist/images/bali4.jpg && cp public/images/bali5.jpg.jpg dist/images/bali5.jpg"
  publish   = "dist"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
